# Generated by Django 5.2.8 on 2025-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('batch_number', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('price', models.IntegerField()),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('colours', models.CharField(max_length=20)),
            ],
        ),
    ]
